version = "Composition1k"
dist = true

[model]
checkpoint = "checkpoints/best_model_mse.pth"
[data]
test_image = "Composition-1k-testset/merged"
test_alpha = "Composition-1k-testset/alphas"
test_trimap = "Composition-1k-testset/trimaps"
test_out = "output"
[classifier]
resume_checkpoint = "checkpoints/fbce.pth"
